version: '3.7'

services:

  users:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app #Pull App Data ub
    ports:
      - 5001:5000
    environment: 
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig #Will need to be parameterized later for install pipeline
      - DATABASE_URL=postgresql://postgres:postgres@users-db:5432/users_dev 
      - DATABASE_TEST_URL=postgresql://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db
  users-db:  # new
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres